image:
  - Visual Studio 2019
  - Ubuntu

environment:
  matrix:
    - TOXENV: py36
      fast_finish: true
      PYTHON: "3.6"
    - TOXENV: py39
      fast_finish: true
      PYTHON: "3.9"

stack: python %PYTHON%

install:
  - SET PATH=%PYTHON%;%PATH%
  - py --version
  - py -m pip install tox

build: off

test_script:
  - py -m tox -e %TOXENV%

artifacts:
  - path: 'abmatt\dist\abmatt_*.tar.gz'
    name: Abmatt-tar

before_deploy:
  - cd abmatt/build
  - echo %APPVEYOR_BUILD_VERSION%
  - py build.py %APPVEYOR_BUILD_VERSION%
  - cd ../..

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  environment:
    matrix:
      - TOXENV: py36
        fast_finish: true
        PYTHON: "C:\\Python36"
      - TOXENV: py39
        fast_finish: true
        PYTHON: "C:\\Python39"

  before_deploy:
    # NSIS
    - ps choco install nsis.install
    - set "PATH=%PATH%;C:\Program Files (x86)\NSIS"
    - curl -fsS https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip -o plugin.zip
    - 7z x plugin.zip -o"C:\Program Files (x86)\NSIS"
    - cd abmatt/build
    - echo %APPVEYOR_BUILD_VERSION%
    - build.py %APPVEYOR_BUILD_VERSION%
    - cd ../..

  artifacts:
    - path: 'abmatt\dist\abmatt_*.zip'
      name: Abmatt-zip


deploy:
  release: ABMatt v$(APPVEYOR_BUILD_VERSION)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 6KTk86aiAEvcI6ogZAbY8iW75JpWLvs2vipWcPfIdWDQKoXsdpzq7tP5Zaq8jdrn
  artifact: Abmatt-zip Abmatt-tar
  draft: true
  prerelease: false
  on:
    branch:
      - release
      - master