image:
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON: C:\Python39-x64
      PYTHON_VERSION: 3.9
      fast_finish: true

    - PYTHON: C:\Python39
      PYTHON_VERSION: 3.9
      fast_finish: true


install:
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Setup python
  - python --version
  - python -c "import sys, platform, struct;
    print(sys.platform, platform.machine(), struct.calcsize('P')*8)"
  - python -m pip install -U --force-reinstall pip
  - python -m easy_install -U setuptools
  - pip install -r requirements.txt --user

  # NSIS
  - ps choco install nsis.install
  - set "PATH=%PATH%;C:\Program Files (x86)\NSIS"
  - curl -fsS https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip -o plugin.zip
  - 7z x plugin.zip -o"C:\Program Files (x86)\NSIS"

build_script:
  - pip install -e .
  - cd abmatt/build
  - echo %APPVEYOR_BUILD_VERSION%
  - build.py %APPVEYOR_BUILD_VERSION%
  - cd ../..

test_script:
  - tox

artifacts:
  - path: 'abmatt\dist\abmatt_*.zip'
    name: Abmatt-zip
  - path: 'abmatt\dist\abmatt_*.tar.gz'
    name: Abmatt-tar

deploy:
  release: ABMatt v$(APPVEYOR_BUILD_VERSION)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 6KTk86aiAEvcI6ogZAbY8iW75JpWLvs2vipWcPfIdWDQKoXsdpzq7tP5Zaq8jdrn
  artifact: Abmatt-zip Abmatt-tar
  draft: true
  prerelease: false
  on:
    branch:
      - release
      - master